title: AI & Society
description: Syllabus for the course ID5417 Artificial Intelligence & Society (2021/2022 Q3)
remote_theme: just-the-docs/just-the-docs
footer_content: "<a href="https://creativecommons.org/licenses/by/4.0/">CC-BY</a> 2020-2022 Kars Alfrink &amp; Gerd Kortuem, Delft University of Technology."
